name: lint

on: [push, pull_request]

jobs:
  lint:
    name: Run linters

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup NPM v7.20.2
        run: npm install -g npm@7.20.2

      - name: Log NPM version
        run: |
          npm --version &&
          npm list -g --depth 0

      - run: npm ci

      - run: npm run lint
