name: test

on: [push, pull_request]

jobs:
  test:
    name: Run tests

    strategy:
      matrix:
        node-version: [14, 16]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup NPM v7
        run: npm install -g npm@7

      - name: Log NPM version
        run: |
          npm --version &&
          npm list -g --depth 0

      - run: npm ci

      - run: npm test
